{{- if .Values.ingress.enabled }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.Version }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ include "codeveros.fullname" . }}
  labels:
  {{- include "codeveros.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
          - path: /api
            backend:
              serviceName: {{ include "codeveros.gatewayService" . }}
              servicePort: 8080
          - path: /
            backend:
              serviceName: {{ include "codeveros.uiService" . }}
              servicePort: 80
      {{- if .Values.ingress.hostName }}
      host: {{ .Values.ingress.hostName | quote }}
      {{- end }}
{{- end }}
