apiVersion: v2
name: codeveros-training-service
description: Codeveros Training Service Helm chart
type: application
version: 0.5.0
appVersion: "1.1"
home: https://coveros.com
maintainers:
  - name: justin-coveros
    email: justin.hollingsworth@coveros.com
dependencies:
  - name: mongodb
    version: 10.3.3
    repository: https://charts.bitnami.com/bitnami
