apiVersion: v2
name: codeveros-auth-service
description: Codeveros Auth Service Helm chart
type: application
version: 0.4.2
appVersion: "1.0"
home: https://coveros.com
maintainers:
  - name: justin-coveros
    email: justin.hollingsworth@coveros.com
