apiVersion: v2
name: codeveros-ui
description: Codeveros Angular UI Helm chart
type: application
version: 0.5.0
appVersion: 1.0
home: https://coveros.com
maintainers:
  - name: justin-coveros
    email: justin.hollingsworth@coveros.com
