apiVersion: v2
name: codeveros-user-service
description: Codeveros User Service Helm chart
type: application
version: 0.2.0
appVersion: latest
dependencies:
  - name: mongodb
    version: 7.8.4
    repository: https://kubernetes-charts.storage.googleapis.com
