replicaCount: 1

image:
  repository: coveros/codeveros-user-service
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []

service:
  type: ClusterIP
  port: 8080

env:
  dbPort: "27017"
  dbDatabase: "users"

mongodb:
  # codeveros currently doesn't use authentication between the service and the database
  usePassword: false
  nameOverride: user-service-mongodb
